title: "Dr Richard Michael Gunner - Postdoctoral Researcher"
author:
  email:
    - "rgunner@ab.mpg.de"
    - "richard.m.g@hotmail.com"
description: >-

  I specialize in wildlife tracking,
  ecological data analysis, and exploring motion sensor data to uncover
  animal behaviors. Discover my projects, publications, and tools.
baseurl: "/my-website"
url: "https://richard6195.github.io"
github_username: "https://github.com/Richard6195"
social_links:
  researchgate: "https://www.researchgate.net/profile/Richard-Gunner-2"
  orcid: "https://orcid.org/0000-0002-2054-9944"

# Build settings
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - index.md
  - about.md
  - projects.md
  - publications.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
